### ISSUE TITLE
Mentioner fail in v1.14.1 when create a ticket

### ISSUE THREAD

**Issue by pablodgonzalez** [clonemeagain/osticket-plugin-mentioner#12]
The function $ticket = $this->getTicket ( $entry ); return a null ticket.
`
[11-Feb-2020 13:41:44 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getRecipients() on null in /home/support_senzil/support.senzil.com/include/plugins/mentioner/class.MentionerPlugin.php:157
Stack trace:
#0 /home/support_senzil/support.senzil.com/include/plugins/mentioner/class.MentionerPlugin.php(49): MentionerPlugin->notifyCollaborators(Object(MessageThreadEntry))
#1 /home/support_senzil/support.senzil.com/include/class.signal.php(98): MentionerPlugin->{closure}(Object(MessageThreadEntry), NULL)
#2 /home/support_senzil/support.senzil.com/include/class.thread.php(1788): Signal::send('threadentry.cre...', Object(MessageThreadEntry))
#3 /home/support_senzil/support.senzil.com/include/class.thread.php(1794): ThreadEntry::create(Array)
#4 /home/support_senzil/support.senzil.com/include/class.thread.php(2914): ThreadEntry::add(Array)
#5 /home/support_senzil/support.senzil.com/include/class.thread.php(3129): MessageThreadEntry::add(Array, Array)
#6 /home/support_senzil/support.senzil.com/include/class.ticket.php(3047): ObjectThread->addMes in /home/support_senzil/support.senzil.com/include/plugins/mentioner/class.MentionerPlugin.php on line 157
`

**Comment by DanielKng** [comment]
See this:
https://github.com/clonemeagain/osticket-plugin-mentioner/issues/11#issuecomment-573572279

**Comment by jevansfbcmb** [comment]
@DanielKng this still does not fix the # error in the newer versions of osT
