### ISSUE TITLE
Issue with #mention with a dot

### ISSUE THREAD

**Issue by JVC-MSF-OCB** [clonemeagain/osticket-plugin-mentioner#14]
Hey there,

Whenever I use the mention #firstname.lastname with a dot I receive an error:

Fatal error: Uncaught InvalidArgumentException: User expected in /var/www/html/include/class.user.php:1460 Stack trace: #0 /var/www/html/include/plugins/mentioner/class.MentionerPlugin.php(92): UserList->add() #1 /var/www/html/include/plugins/mentioner/class.MentionerPlugin.php(48): MentionerPlugin->checkThreadTextForMentions() #2 /var/www/html/include/class.signal.php(98): MentionerPlugin->{closure}() #3 /var/www/html/include/class.thread.php(1806): Signal::send() #4 /var/www/html/include/class.thread.php(1812): ThreadEntry::create() #5 /var/www/html/include/class.thread.php(3030): ThreadEntry::add() #6 /var/www/html/include/class.thread.php(3152): NoteThreadEntry::add() #7 /var/www/html/include/class.ticket.php(3537): ObjectThread->addNote() #8 /var/www/html/scp/tickets.php(266): Ticket->postNote() #9 {main} thrown in /var/www/html/include/class.user.php on line 1460

Any idea what this means? How to solve this? @clonemeagain

**Comment by logmsf** [comment]
Hey man,
Have you managed to give it a look? Are you still planning to maintain this plugin?
